# Generated by Django 5.1.4 on 2024-12-26 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=255)),
                ('maincode', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('author', models.TextField(blank=True, null=True)),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('type', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'news',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(blank=True, max_length=255, null=True)),
                ('subgroup', models.CharField(blank=True, max_length=255, null=True)),
                ('feature', models.CharField(blank=True, max_length=255, null=True)),
                ('packaging', models.CharField(blank=True, max_length=255, null=True)),
                ('weightvolume', models.CharField(blank=True, max_length=255, null=True)),
                ('factory', models.CharField(blank=True, max_length=255, null=True)),
                ('productname', models.CharField(blank=True, max_length=255, null=True)),
                ('itemrowcode', models.CharField(blank=True, max_length=255, null=True)),
                ('productcode', models.CharField(blank=True, max_length=255, null=True)),
                ('itemcode', models.CharField(blank=True, max_length=255, null=True)),
                ('unit', models.CharField(blank=True, max_length=255, null=True)),
                ('productitemcode', models.CharField(blank=True, max_length=255, null=True)),
                ('category_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'products',
                'managed': False,
            },
        ),
    ]
